### PR TITLE
Force the markdown filter for Obsidian documents.

### LINKED ISSUE #9: Antidote (Connectix) open API does not support Markdown formatting
- **I'm submitting a ...**
  [X] bug report

- **Summary**

Before using the open API of Connectix, this project uses the old private API. The private API supported markdown formatting into Antidote.

Currently, with the open API, it seems not working.

Does the open API support it? If yes, how can we support it?

Ping @Acibi @alaroucheDruide

Here is a diff:

## With (old) private API
With (old) private API

## With open API
With open API

### PR DESCRIPTION
**Pull request by Acibi**
Close #9

### CODE REVIEW

**Comment by Heziode** [comment]
It could be nice to have a documentation of all possible values of `laReponse.filtreActif`.

Obsidian main target is Markdown, but users can also open any kind of file (text or binary), so, only forcing Markdown is not the best solution IMHO.

**Comment by Acibi** [comment]
We are currently working on an official documentation for the API.

If the "filtreActif" option is not set, Antidote will try to detect the best filter to apply to the document.

Otherwise, you can choose one of the following filters to be applied : 

"texte"
"markdown"
"latex"
"subrip"

**Comment by Heziode** [comment]
I do not have the right to push to your branch, so, can you apply the following patch please, to support all supported format:
[Update_`DonneTypeDocument`_to_support_all_Antidote_supported_format.patch](https://github.com/Heziode/obsidian-antidote/files/10561861/Update_.DonneTypeDocument._to_support_all_Antidote_supported_format.patch)

Furthermore, I tested on my side, and the formatting does not work.
macOS: 13.1 (22C65)
Antiode: 11.2.4317
Connectix: 11.2.1 (1102.46.27)

**Comment by Heziode** [comment]
Thank you for the update.

I tested on my side, and the formatting still does not work.
macOS: 13.1 (22C65)
Antiode: 11.2.4317
Connectix: 11.2.1 (1102.46.27)

CleanShot 2023-02-02 at 22 10 53@2x

Is a specific version of Connectix needed?

**Comment by alaroucheDruide** [comment]
We'll be including the fix in the upcoming update - 11 v3.2, due next week.

**Pull request merged**
